export const menuItems = [
    {
        id: 1,
        menu: 'menu item 1',
        sub: [
            { name: 'sub item 1', id: 1, url: '/terms-and-conditions' },
            { name: 'sub item 2', id: 2, url: '/home' },
            { name: 'sub item 3', id: 3, url: '/home' },
            { name: 'sub item 4', id: 4, url: '/home' },
            { name: 'sub item 5', id: 5, url: '/home' },
            { name: 'sub item 6', id: 6, url: '/home' },
        ],
    },
    {
        id: 2,
        menu: 'menu item 2',
        sub: [
            { name: 'sub item 1', id: 1, url: '/home' },
            { name: 'sub item 2', id: 2, url: '/home' },
            { name: 'sub item 3', id: 3, url: '/home' },
            { name: 'sub item 4', id: 4, url: '/home' },
            { name: 'sub item 5', id: 5, url: '/home' },
            { name: 'sub item 6', id: 6, url: '/home' },
        ],
    },

    {
        id: 3,
        menu: 'menu item 3',
        sub: [
            { name: 'sub item 1', id: 1, url: '/home' },
            { name: 'sub item 2', id: 2, url: '/home' },
            { name: 'sub item 3', id: 3, url: '/home' },
            { name: 'sub item 4', id: 4, url: '/home' },
            { name: 'sub item 5', id: 5, url: '/home' },
            { name: 'sub item 6', id: 6, url: '/home' },
            { name: 'sub item 1', id: 1, url: '/home' },
            { name: 'sub item 2', id: 2, url: '/home' },
            { name: 'sub item 3', id: 3, url: '/home' },
            { name: 'sub item 4', id: 4, url: '/home' },
            { name: 'sub item 5', id: 5, url: '/home' },
            { name: 'sub item 6', id: 6, url: '/home' },
            { name: 'sub item 1', id: 1, url: '/home' },
            { name: 'sub item 2', id: 2, url: '/home' },
            { name: 'sub item 3', id: 3, url: '/home' },
            { name: 'sub item 4', id: 4, url: '/home' },
            { name: 'sub item 5', id: 5, url: '/home' },
            { name: 'sub item 6', id: 6, url: '/home' },
            { name: 'sub item 1', id: 1, url: '/home' },
            { name: 'sub item 2', id: 2, url: '/home' },
            { name: 'sub item 3', id: 3, url: '/home' },
            { name: 'sub item 4', id: 4, url: '/home' },
            { name: 'sub item 5', id: 5, url: '/home' },
            { name: 'sub item 6', id: 6, url: '/home' },
        ],
    },
];
